
dependencies:
  - python=3.7
  - sqlite>=3.35                 # need 3.35 which has sqrt function
  - libcurl
  - cmake
  - pip
  - automake
  - pip:
      - flex
      - bison
      - libmagic
      - keras==2.2.5
      - keras-rectified-adam==0.17.0
      - matplotlib
      - progressbar2
      - tqdm
      - ansicolors
      - imageio
      - scikit-image
      - sklearn
      - pandas
      - -e .
